spring.application.name=API
# Credenciales directas de Neon
spring.datasource.url=jdbc:postgresql://ep-square-dream-b4twmtql-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_0PBjrZb4ezux
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA (Tus Entidades)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true